/**
 * @file    User_ADC.c
 * @brief   ADC 驱动实现 —— 注入模式相电流校准
 * @author  Auto-generated by AI
 * @date    2026-05-04
 *
 * @note    STEP5: 注入同步模式, TIM1_TRGO 触发。
 *          校准用软件触发逐一采样 100 次取均值为零点。
 */
#include "User_ADC.h"

/* ======================== 私有变量 ======================== */

static ADC_HandleTypeDef *adc1_handle = NULL;
static ADC_HandleTypeDef *adc2_handle = NULL;

uint16_t adc_zero_ia = ADC_ZERO_CURRENT_THEORY;
uint16_t adc_zero_ib = ADC_ZERO_CURRENT_THEORY;

static uint8_t adc_is_init = 0;

/* ======================== 公共函数实现 ======================== */

int ADC_Init(ADC_HandleTypeDef *hadc1, ADC_HandleTypeDef *hadc2)
{
    if (hadc1 == NULL || hadc2 == NULL) {
        return -1;
    }

    adc1_handle = hadc1;
    adc2_handle = hadc2;
    adc_is_init = 1;

    return 0;
}

int ADC_Calibrate(void)
{
    uint32_t sum_ia = 0;
    uint32_t sum_ib = 0;
    int i;

    if (adc_is_init == 0) {
        return -1;
    }

    /* 常规组校准: 直接操作寄存器 SWSTART → 轮询 EOC → 读 DR
       常规组与注入组共存, 互不冲突, 绕开 HAL 状态机限制 */
    for (i = 0; i < ADC_CALIBRATE_SAMPLES; i++) {
        /* ADC1 常规组软件触发 */
        __HAL_ADC_CLEAR_FLAG(adc1_handle, ADC_FLAG_JEOC);
        __HAL_ADC_CLEAR_FLAG(adc2_handle, ADC_FLAG_JEOC);

        if (HAL_ADCEx_InjectedStart(adc2_handle) != HAL_OK) {
            return -2;
        }
        if (HAL_ADCEx_InjectedStart(adc1_handle) != HAL_OK) {
            HAL_ADCEx_InjectedStop(adc2_handle);
            return -3;
        }

        if (HAL_ADCEx_InjectedPollForConversion(adc1_handle,
                                                ADC_READ_TIMEOUT) != HAL_OK) {
            HAL_ADCEx_InjectedStop(adc1_handle);
            HAL_ADCEx_InjectedStop(adc2_handle);
            return -4;
        }

        sum_ia += HAL_ADCEx_InjectedGetValue(adc1_handle,
                                             ADC_INJECTED_RANK_1);

        /* ADC2 常规组软件触发 */
        sum_ib += HAL_ADCEx_InjectedGetValue(adc2_handle,
                                             ADC_INJECTED_RANK_1);

        HAL_ADCEx_InjectedStop(adc1_handle);
        HAL_ADCEx_InjectedStop(adc2_handle);

        HAL_Delay(1);
    }

    adc_zero_ia = (uint16_t)(sum_ia / ADC_CALIBRATE_SAMPLES);
    adc_zero_ib = (uint16_t)(sum_ib / ADC_CALIBRATE_SAMPLES);

    return 0;
}
