/**
 * @file    User_ADC.c
 * @brief   ADC 驱动实现 —— 注入模式相电流校准
 * @author  Auto-generated by AI
 * @date    2026-05-04
 *
 * @note    STEP5: 注入同步模式, TIM1_TRGO 触发。
 *          校准用软件触发逐一采样 100 次取均值为零点。
 */
#include "User_ADC.h"

/* ======================== 私有变量 ======================== */

static ADC_HandleTypeDef *adc1_handle = NULL;
static ADC_HandleTypeDef *adc2_handle = NULL;

uint16_t adc_zero_ia = ADC_ZERO_CURRENT_THEORY;
uint16_t adc_zero_ib = ADC_ZERO_CURRENT_THEORY;

static uint8_t adc_is_init = 0;

/* ======================== 公共函数实现 ======================== */

int ADC_Init(ADC_HandleTypeDef *hadc1, ADC_HandleTypeDef *hadc2)
{
    if (hadc1 == NULL || hadc2 == NULL) {
        return -1;
    }

    adc1_handle = hadc1;
    adc2_handle = hadc2;
    adc_is_init = 1;

    return 0;
}

int ADC_Calibrate(void)
{
    uint32_t sum_ia = 0;
    uint32_t sum_ib = 0;
    uint32_t tick;
    int i;

    if (adc_is_init == 0) {
        return -1;
    }

    /* 常规组校准: 直接操作寄存器 SWSTART → 轮询 EOC → 读 DR
       常规组与注入组共存, 互不冲突, 绕开 HAL 状态机限制 */
    for (i = 0; i < ADC_CALIBRATE_SAMPLES; i++) {
        /* ADC1 常规组软件触发 */
        SET_BIT(adc1_handle->Instance->CR2, ADC_CR2_SWSTART);
        tick = HAL_GetTick();
        while (!(adc1_handle->Instance->SR & ADC_SR_EOC)) {
            if (HAL_GetTick() - tick > ADC_READ_TIMEOUT) {
                return -1;
            }
        }
        sum_ia += adc1_handle->Instance->DR;

        /* ADC2 常规组软件触发 */
        SET_BIT(adc2_handle->Instance->CR2, ADC_CR2_SWSTART);
        tick = HAL_GetTick();
        while (!(adc2_handle->Instance->SR & ADC_SR_EOC)) {
            if (HAL_GetTick() - tick > ADC_READ_TIMEOUT) {
                return -1;
            }
        }
        sum_ib += adc2_handle->Instance->DR;

        HAL_Delay(1);
    }

    adc_zero_ia = (uint16_t)(sum_ia / ADC_CALIBRATE_SAMPLES);
    adc_zero_ib = (uint16_t)(sum_ib / ADC_CALIBRATE_SAMPLES);

    return 0;
}
