/**
 * @file    User_Usart.c
 * @brief   串口打印工具实现
 * @author  Auto-generated by AI
 * @date    2026-05-04
 */
#include "User_Usart.h"
#include <string.h>

/* ======================== 公共函数实现 ======================== */

void USART_Printf(UART_HandleTypeDef *huart, const char *fmt, ...)
{
    char buf[USART_PRINTF_BUF_SIZE];
    va_list args;
    int len;

    /* 参数检查 */
    if (huart == NULL || fmt == NULL) {
        return;
    }

    /* 格式化字符串到缓冲区 */
    va_start(args, fmt);
    len = vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);

    /* 防止 snprintf 写入超出缓冲区 (返回值可能大于 sizeof(buf)) */
    if (len < 0) {
        return;
    }
    if ((size_t)len >= sizeof(buf)) {
        len = (int)(sizeof(buf) - 1);
    }

    /* 通过 HAL 发送 */
    HAL_UART_Transmit(huart, (uint8_t *)buf, (uint16_t)len, HAL_MAX_DELAY);
}

void USART_SendByte(UART_HandleTypeDef *huart, uint8_t byte)
{
    if (huart == NULL) {
        return;
    }
    HAL_UART_Transmit(huart, &byte, 1, HAL_MAX_DELAY);
}

void USART_SendString(UART_HandleTypeDef *huart, const char *str)
{
    if (huart == NULL || str == NULL) {
        return;
    }
    HAL_UART_Transmit(huart, (uint8_t *)str, (uint16_t)strlen(str), HAL_MAX_DELAY);
}
