/**
 * @file    User_AS5600.c
 * @brief   AS5600 磁编码器驱动实现
 * @author  Auto-generated by AI
 * @date    2026-05-04
 */
#include "User_AS5600.h"

/* ======================== 私有变量 ======================== */

/** @brief 内部保存的 I2C 句柄指针 */
static I2C_HandleTypeDef *as5600_i2c_handle = NULL;

/** @brief 设备是否已成功初始化的标志 */
static uint8_t as5600_is_init = 0;

/* ======================== 私有函数声明 ======================== */

/**
 * @brief  从 I2C 设备读取 16 位寄存器值 (MSB 优先)
 * @param  reg_addr: 寄存器起始地址 (支持地址自增)
 * @param  value: 输出值指针
 * @retval 0: 成功
 * @retval -1: I2C 通信失败
 */
static int AS5600_Read16(uint8_t reg_addr, uint16_t *value);

/* ======================== 私有函数实现 ======================== */

static int AS5600_Read16(uint8_t reg_addr, uint16_t *value)
{
    uint8_t buf[2] = {0};
    HAL_StatusTypeDef hal_ret;

    if (as5600_i2c_handle == NULL) {
        return -1;  /* 未初始化 */
    }

    /* 从 reg_addr 起读 2 字节, AS5600 自动地址自增 */
    hal_ret = HAL_I2C_Mem_Read(as5600_i2c_handle,
                                AS5600_I2C_ADDR,
                                reg_addr,
                                I2C_MEMADD_SIZE_8BIT,
                                buf,
                                2,
                                AS5600_I2C_TIMEOUT);

    if (hal_ret != HAL_OK) {
        return -1;  /* I2C 通信失败 */
    }

    /* AS5600 返回 MSB 在前, 组合为 uint16_t */
    *value = ((uint16_t)buf[0] << 8) | buf[1];

    return 0;
}

/* ======================== 公共函数实现 ======================== */

int AS5600_Init(I2C_HandleTypeDef *hi2c)
{
    uint8_t status;

    /* 参数检查 */
    if (hi2c == NULL) {
        return -1;
    }

    as5600_i2c_handle = hi2c;

    /* 尝试读取状态寄存器, 确认设备在线 */
    if (AS5600_GetStatus(&status) != 0) {
        as5600_is_init = 0;
        return -2;  /* I2C 设备无应答 */
    }

    as5600_is_init = 1;
    return 0;
}

int AS5600_ReadRawAngle(uint16_t *angle)
{
    /* 参数检查 */
    if (angle == NULL) {
        return -2;
    }
    if (as5600_is_init == 0) {
        return -1;
    }

    return AS5600_Read16(AS5600_REG_RAW_ANGLE, angle);
}

int AS5600_ReadAngle(uint16_t *angle)
{
    /* 参数检查 */
    if (angle == NULL) {
        return -2;
    }
    if (as5600_is_init == 0) {
        return -1;
    }

    return AS5600_Read16(AS5600_REG_ANGLE, angle);
}

int AS5600_GetStatus(uint8_t *status)
{
    HAL_StatusTypeDef hal_ret;

    /* 参数检查 */
    if (status == NULL) {
        return -2;
    }
    if (as5600_i2c_handle == NULL) {
        return -1;
    }

    /* 读单字节状态寄存器 */
    hal_ret = HAL_I2C_Mem_Read(as5600_i2c_handle,
                                AS5600_I2C_ADDR,
                                AS5600_REG_STATUS,
                                I2C_MEMADD_SIZE_8BIT,
                                status,
                                1,
                                AS5600_I2C_TIMEOUT);

    if (hal_ret != HAL_OK) {
        return -1;
    }

    return 0;
}

int AS5600_IsMagnetDetected(uint8_t *detected)
{
    uint8_t status;
    int ret;

    /* 参数检查 */
    if (detected == NULL) {
        return -2;
    }

    ret = AS5600_GetStatus(&status);
    if (ret != 0) {
        return ret;
    }

    *detected = (status & AS5600_STATUS_MD) ? 1 : 0;
    return 0;
}
