/**
 * @file    User_Usart.h
 * @brief   串口打印工具头文件
 * @author  Auto-generated by AI
 * @date    2026-05-04
 */
#ifndef __USER_USART_H
#define __USER_USART_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f1xx_hal.h"
#include <stdarg.h>
#include <stdio.h>

/* ======================== 宏定义 ======================== */

/** @brief 格式化打印缓冲区大小 */
#define USART_PRINTF_BUF_SIZE   128

/* ======================== 函数声明 ======================== */

/**
 * @brief  串口格式化打印 (类似 printf)
 * @param  huart: UART 句柄指针
 * @param  fmt: 格式化字符串
 * @param  ...: 可变参数
 */
void USART_Printf(UART_HandleTypeDef *huart, const char *fmt, ...);

/**
 * @brief  串口发送单字节
 * @param  huart: UART 句柄指针
 * @param  byte: 待发送字节
 */
void USART_SendByte(UART_HandleTypeDef *huart, uint8_t byte);

/**
 * @brief  串口发送字符串
 * @param  huart: UART 句柄指针
 * @param  str: 待发送字符串 (必须以 '\0' 结尾)
 */
void USART_SendString(UART_HandleTypeDef *huart, const char *str);

#ifdef __cplusplus
}
#endif

#endif /* __USER_USART_H */
