/**
 * @file    User_ADC.h
 * @brief   ADC 驱动头文件 —— 注入模式相电流采样
 * @author  Auto-generated by AI
 * @date    2026-05-04
 *
 * @note    STEP5 起使用注入同步模式 (ADC_DUALMODE_INJECSIMULT),
 *          TIM1_TRGO 硬件触发, ADC1_2 中断内完成 FOC 主循环。
 *          常规组已弃用, 所有轮询 API 移除。
 */
#ifndef __USER_ADC_H
#define __USER_ADC_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f1xx_hal.h"

/* ======================== 通道宏定义 ======================== */

#define ADC1_CH_IA       ADC_CHANNEL_1   /* PA1, A相上端电流采样 */
#define ADC1_CH_TEMP     ADC_CHANNEL_3   /* PA3, 温度传感器       */
#define ADC2_CH_IB       ADC_CHANNEL_2   /* PA2, B相上端电流采样 */

/* ======================== 硬件参数宏 ======================== */

#define INA199_REF_VOLTAGE      1.65f
#define INA199_SHUNT_RESISTANCE 0.02f
#define INA199_GAIN             50.0f
#define ADC_VREF                3.3f
#define ADC_RESOLUTION          4096
#define ADC_ZERO_CURRENT_THEORY 2048
#define ADC_CALIBRATE_SAMPLES   100
#define ADC_READ_TIMEOUT        10

/* ======================== 换算宏 ======================== */

#define ADC_TO_VOLTAGE(adc_val)   ((float)(adc_val) * ADC_VREF / (float)ADC_RESOLUTION)

#define ADC_TO_CURRENT(adc_val, zero) \
    (((float)((int32_t)(adc_val) - (int32_t)(zero))) * ADC_VREF \
     / ((float)ADC_RESOLUTION * INA199_GAIN * INA199_SHUNT_RESISTANCE))

#define ADC_TO_CURRENT_MA(adc_val, zero) \
    ((int32_t)(ADC_TO_CURRENT(adc_val, zero) * 1000.0f))

#define ADC_TO_VOLTAGE_MV(adc_val) \
    ((int32_t)(ADC_TO_VOLTAGE(adc_val) * 1000.0f))

/* ======================== 外部变量 ======================== */

extern uint16_t adc_zero_ia;
extern uint16_t adc_zero_ib;

/* ======================== 函数声明 ======================== */

int ADC_Init(ADC_HandleTypeDef *hadc1, ADC_HandleTypeDef *hadc2);
int ADC_Calibrate(void);

#ifdef __cplusplus
}
#endif

#endif /* __USER_ADC_H */
