/**
 * @file    User_AS5600.h
 * @brief   AS5600 磁编码器驱动头文件
 * @author  Auto-generated by AI
 * @date    2026-05-04
 */
#ifndef __USER_AS5600_H
#define __USER_AS5600_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f1xx_hal.h"

/* ======================== 宏定义 ======================== */

/** @brief AS5600 I2C 从机地址 (7-bit 0x36, HAL 需左移 1 位) */
#define AS5600_I2C_ADDR          (0x36 << 1)

/** @brief AS5600 寄存器地址定义 */
#define AS5600_REG_ZMCO          0x00   /* 零点编程次数 (只读) */
#define AS5600_REG_ZPOS_H        0x01   /* 零点位置 高 4 位 */
#define AS5600_REG_ZPOS_L        0x02   /* 零点位置 低 8 位 */
#define AS5600_REG_MPOS_H        0x03   /* 最大位置 高 4 位 */
#define AS5600_REG_MPOS_L        0x04   /* 最大位置 低 8 位 */
#define AS5600_REG_MANG_H        0x05   /* 最大角度 高 4 位 */
#define AS5600_REG_MANG_L        0x06   /* 最大角度 低 8 位 */
#define AS5600_REG_CONF_H        0x07   /* 配置寄存器 高 8 位 */
#define AS5600_REG_CONF_L        0x08   /* 配置寄存器 低 8 位 */
#define AS5600_REG_STATUS        0x0B   /* 状态寄存器 (磁铁检测等) */
#define AS5600_REG_RAW_ANGLE     0x0C   /* 原始角度 高 4 位 (地址自增读取 0x0C~0x0D) */
#define AS5600_REG_ANGLE         0x0E   /* 滤波角度 高 4 位 (地址自增读取 0x0E~0x0F) */

/** @brief STATUS 寄存器位掩码 */
#define AS5600_STATUS_MD         (1 << 5)  /* 磁铁检测到 */
#define AS5600_STATUS_ML         (1 << 4)  /* 磁铁太弱 */
#define AS5600_STATUS_MH         (1 << 3)  /* 磁铁太强 */

/** @brief 角度分辨率 */
#define AS5600_RESOLUTION        4096     /* 12-bit 分辨率, 0 ~ 4095 */

/** @brief I2C 通信超时 (ms) */
#define AS5600_I2C_TIMEOUT       10

/* ======================== 函数声明 ======================== */

/**
 * @brief  初始化 AS5600 驱动
 * @param  hi2c: I2C 句柄指针 (已通过 CubeMX 初始化)
 * @retval 0: 成功
 * @retval -1: 参数为空
 * @retval -2: I2C 设备无应答
 */
int AS5600_Init(I2C_HandleTypeDef *hi2c);

/**
 * @brief  读取原始角度 (RAW_ANGLE, 0x0C)
 * @param  angle: 输出角度值指针 (范围 0 ~ 4095)
 * @retval 0: 成功
 * @retval -1: I2C 通信失败
 * @retval -2: 参数为空
 */
int AS5600_ReadRawAngle(uint16_t *angle);

/**
 * @brief  读取滤波角度 (ANGLE, 0x0E, 带滞回和零点补偿)
 * @param  angle: 输出角度值指针 (范围 0 ~ 4095)
 * @retval 0: 成功
 * @retval -1: I2C 通信失败
 * @retval -2: 参数为空
 */
int AS5600_ReadAngle(uint16_t *angle);

/**
 * @brief  读取状态寄存器 (STATUS, 0x0B)
 * @param  status: 输出状态字节指针
 * @retval 0: 成功
 * @retval -1: I2C 通信失败
 * @retval -2: 参数为空
 */
int AS5600_GetStatus(uint8_t *status);

/**
 * @brief  检测磁铁是否在位
 * @param  detected: 输出检测结果 (1 = 磁铁在位, 0 = 磁铁未检测到)
 * @retval 0: 成功
 * @retval -1: I2C 通信失败
 * @retval -2: 参数为空
 */
int AS5600_IsMagnetDetected(uint8_t *detected);

#ifdef __cplusplus
}
#endif

#endif /* __USER_AS5600_H */
